### ISSUE TITLE
Providing typing annotations

### ISSUE THREAD

**Issue by playpauseandstop** [hynek/environ-config#15]
Hi,

After adding `environ-config` to my projects with strict mypy config, I needed to provide numerous `# type: ignore` comments as `environ` is not typed yet.

I would like to provide type annotations for `environ-config`, but need to know several moments,

1. Should I provide annotations in Python files or via `*.pyi` files as done in `attrs`?
2. I’ve seen that in attrs typing annotations checked by running mypy over `src/attr/*.pyi` files and over `tests/typing_example.py` file. I understand necessity of providing similar `typing_example.py` file for `environ-config` as well, but not sure in its content. Can you provide suggestions on what needed to be “tested” there?
3. I’ve seen that `tox.ini` contains unpinned mypy. Would it be better to run typing checks agains pinned mypy version instead? What about adding mypy pre-commit hook instead of tox env or alongside?

Any other suggestions on a topic are welcome

**Comment by 0az** [comment]
Well, this is amusing – I started looking into this independently over the past couple weeks, and was just about to file this exact issue.

I think a good way to do this is to hook into the existing MyPy support for `attrs`. Right now, I'm experimenting locally with monkey-patching the `attrs` plugin [0]. Don't have it published yet, though. I'll see what I can quickly push.

> Should I provide annotations in Python files or via *.pyi files as done in attrs?
`*.pyi` is better for compatibility, I think.

[0] <https://github.com/python/mypy/blob/master/mypy/plugins/attrs.py#L33-L45>

**Comment by hynek** [comment]
Would https://github.com/python-attrs/attrs/issues/630#issuecomment-607281253 help?

As for how: I'm considering to make environ-config 3.6+ since I don't expect any major features that are needed for 2.7 too – change my mind. ;)

**Comment by Frank5000** [comment]
> As for how: I'm considering to make environ-config 3.6+ since I don't expect any major features that are needed for 2.7 too – change my mind. ;)

Yes please

**Comment by hynek** [comment]
I have added type hints for public APIs in #49 – please LMK if that helps y'all.

**Comment by playpauseandstop** [comment]
Thanks a lot for PR, it helps for sure!

**Comment by hynek** [comment]
Fixed by #49, please open new issues if something is off.
