### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by HerHde** [hynek/environ-config#16]
Hey there, thanks for this nice lib.

I had some issues to get some log output. The doc says:

> The other option is to activate debug-level logging for the environ_config logger by setting its level to logging.WARNING.

It took me some time to understand that I need to set `logging.getLogger('environ_config').setLevel('DEBUG')`, maybe this would be a nice addition to the docs.

Furthermore it says, that the log level should be *WARNING*, however the messages are logged as *DEBUG*.

Finally, it would be nice to not only log that the variables are looked up, but also whether they are found and what their value is.

Cheers!

**Comment by hynek** [comment]
I have fixed the doc in but the changes to log output would be more complex than I am willing to put work into because of the handling of default values. Thanks, for the report!
