### ISSUE TITLE
Adding leading _ even with prefix=""

### ISSUE THREAD

**Issue by brenramz** [hynek/environ-config#18]
Hi, I am using the latest version but when I do `help_str = environ.generate_help(AppConfig)` where 
```
@environ.config(prefix="")
class Parent:
      example1= environ.var(default="example 1")
      example2 = environ.var(default="example2")
```
I getting:
```
_EXAMPLE_1
_EXAMPLE_2
```
It just happend when showing vars, because when setting EXAMPLE_1 and EXAMPLE_2, are right.

**Comment by hynek** [comment]
I think this was fixed in #14? Sorry for the late response.
