### ISSUE TITLE
Generate JSON

### ISSUE THREAD

**Issue by Chris-May** [hynek/environ-config#26]
What do you think about adding a method to generate a JSON string from a configuration class?

I created a method for `environ.config` classes in a couple of recent projects to take their help strings and convert it to JSON. My teammates and I loved the convenience of knowing for sure we had all configuration values covered.

We found it most helpful when adding someone to the team or preparing to deploy to a new environment. We could run `AppConfig.generate_json()`, pipe the output into a file, and edit the file with the needed configuration values.

This was inspired by similar functionality in [goodconf](https://github.com/lincolnloop/goodconf).

**Comment by Chris-May** [comment]
Huh. I apparently hit the close button on my last comment.

**Comment by Chris-May** [comment]
Hey, @hynek!

I was thinking about what would be best for a `generate_dict` method to return, and I wanted to get your thoughts.

If we take one of the test examples:
```python
@environ.config(prefix="APP")
class AppConfig:
    host = environ.var("127.0.0.1", help="host help")
    port = environ.var(5000, converter=int, help="port help")
```

One option could be to return one dictionary whose keys are the provided variable names and values are essentially the current help dictionaries:
```python
>>> AppConfig.generate_dict()
{        
    'host': {
        'required': False,
        'default': '127.0.0.1',
        'help_str': 'host help',
        'var_name': 'APP_HOST'
    },
    'port': {
        'required': False,
        'default': 5000,
        'help_str': 'port help',
        'var_name': 'APP_PORT'
    },
}
```

I like this option, keeping the current help dictionaries relatively intact. 

Another option is to change the keys to the environmental variables:
```python
>>> AppConfig.generate_dict()
{        
    'APP_HOST': {
        'required': False,
        'default': '127.0.0.1',
        'help_str': 'host help'
    },
    'APP_PORT': {
        'required': False,
        'default': 5000,
        'help_str': 'port help'
    },
}
```
Do you like either of these options? Is there a better solution that comes to mind?

**Comment by hynek** [comment]
I think the former shape is better, because we can't anticipate what people want to do with the data. You can always get from shape 1 to shape 2 easily unless I'm missing something.

**Comment by Chris-May** [comment]
I'm sorry, @hynek. I've been excited to do this, but things keep getting in the way. I feel bad for having an open issue for all this time.

**Comment by hynek** [comment]
Heh don't worry about it; it's but a drop in the ocean
