### ISSUE TITLE
[Question] Is controlling `on_setattr` possible?

### ISSUE THREAD

**Issue by leroyvn** [hynek/environ-config#32]
# Use case

I'm using *environ-config* to conveniently maintain configuration data and display config options in my docs. The software I'm writing is basically a scientific analysis library, meant to be used in an interactive console such as a Jupyter notebook. In this workflow, it may be desirable to modify the configuration during execution.

# The issue

I'd like converters to be executed when setting variables. Is there a built-in option similar to `attrs`' `on_setattr` to do that? Or should I work around it?

**Comment by hynek** [comment]
Ah sorry I missed this one, otherwise I would’ve looked at it before pushing 22.1. You should be able to make that work by copy/pasting https://github.com/hynek/environ-config/blob/9a580a861df0d163139b5ab065ef85ddc2bbb99d/src/environ/_environ_config.py#L120-L146 and adding on_setattr.

**Comment by leroyvn** [comment]
Thanks @hynek, this is just what I need :)

**Comment by hynek** [comment]
I'm gonna close this for now since it doesn't seem too common of a problem and supporting it would raise our minimum attrs version.
