### ISSUE TITLE
How to access nested section value?

### ISSUE THREAD

**Issue by arseniiarsenii** [hynek/environ-config#34]
I have created a nested config structure:

```python
@environ.config(prefix="", frozen=True)
class Config:

    @environ.config(frozen=True)
    class MongoDB:
        mongo_connection_uri: str = environ.var(help="Your MongoDB connection URI")
    ...

    db = environ.group(MongoDB)
    ...
```

However, accessing a nested group member like this:
`Config.db.mongo_connection_uri`

Produces following error:
```
 AttributeError: 'member_descriptor' object has no attribute 'mongo_connection_uri'
```

I could not find an example of accessing a member of a group in the docs, so I created this issue. How should I access a member of a config group?

Thank you.

**Comment by hynek** [comment]
It looks like you didn’t load the config and are trying to access the instance fields on the class?

**Comment by arseniiarsenii** [comment]
@hynek I load it from the environment variables later in the same file:
```python
if __name__ == "__main__":
    print(environ.generate_help(Config))
else:
    environ.to_config(Config)
```

And in my other modules I import the class. Does `environ.to_config(Config)` return an instance which I should import instead?

**Comment by arseniiarsenii** [comment]
> Does `environ.to_config(Config)` return an instance which I should import instead?

Indeed it does. This fixed the issue for me.
