### ISSUE TITLE
How to set other values for the same APP_ENV for a pytest case?

### ISSUE THREAD

**Issue by adrianovieira** [hynek/environ-config#43]
Hi!

I built an api with fastpi, and I am using this module to set some variables.

My issue is that I am trying to `pytest` it by setting other values for the same environment variables, but the `environ-config` only read once per pytest execution.

For example, we have different places to test the API, e.g: APP_PLACE=EU, APP_PLACE=Americas etc.

So we can use `os.environ` to set pytest and environ-config to get the new value for that environment variable to check..  but the `environ-config` only reads once per pytest execution.

What do I need to do to fix that?

PS: bellow a "hello world" app as an example of what I need to test.

- pytest `conftest.py`:
<Details>

```python
# conftest.py
from fastapi.testclient import TestClient
import os
import pytest

@pytest.fixture()
def client():
    from main import app

    yield TestClient(app)
    

@pytest.fixture()
def client_env():
    os.environ['APP_PLACE'] = 'EU'
    from main import app as app_env
    
    yield TestClient(app_env)
```
</Details>

- pytest test case `hello_test.py`:

<Details>

```python
# hello_test.py
from fastapi.testclient import TestClient
import os

class TestHello:
    
    def test_get_main_index(self, client: TestClient):
        response = client.get("/")
        assert response.status_code == 200
        assert response.json() == {'Hello': 'World'}


    def test_get_main_env_world_placeed(self, client_env: TestClient):
        response = client_env.get("/My World place")
        
        assert response.status_code == 200
        place = os.environ['APP_PLACE']
        assert response.json() == {'Hello': 'My World place', "place": place}
```
</Details>

- `config.py`:
<Details>

```python
# config.py
from environ import config, to_config, var

@config
class Config:
    PLACE: str = var(default=None)
    
CONFIG: Config = to_config(Config)
```
</Details>

- `main.py`: 
<Details>

```python
# main.py
from fastapi import FastAPI

from app.config import CONFIG

app = FastAPI()

@app.get("/")
def hello():
    return {'Hello': 'World'}


@app.get("/{env_world}")
def hello_env_world(env_world: str):
    place = CONFIG.PLACE
    result = {"Hello": env_world} if not place else {"Hello": env_world, "place": place}
    return result
```

</Details>

You can also get or see this code on my repo:  https://github.com/adrianovieira/hello-pytest-env

**Comment by hynek** [comment]
The problem you're running into is exactly the reason why this kind of global configuration (that afaik has been popularized by Flask) is problematic.

Your config.py is the interface to the world and CONFIG is loaded on import time – there isn't much you can do here except monkeypatching, which would be my reluctant suggestion for a quick fix.

---

In a more general vein, what I do in my projects is having one application entry point that does the loading of environments (for wsgi apps, I call them `wsgi.py`): they import Config from `.config`, load it, configure logging, and then call an app factory that instantiates the application (in Flask's case using Blueprints – I presume FastAPI has an equivalent):

```python
import environ

from .app_maker import make_app
from .config import AppConfig
from .logging import setup_logging

app_cfg = environ.to_config(AppConfig)

setup_logging(app_cfg)
application = make_app(app_cfg)
```

And now I run e.g. `gunicorn app.wsgi:application` (`:application` is default & optional)

---

That means I can configure my application like I want for every test, without patching around the environment:

```python
def pytest_configure():
    for k, v in [
        ("ENV", "test"),
        ("SECRETS_INI", "test-secrets.ini"),
    ]:
        os.environ["APP_" + k] = v

@pytest.fixture(name="app_cfg", scope="session")
def _app_cfg():
    """
    Loads the configuration delayed, i.e. after pytest_configure was able to
    patch the environment.
    """
    return environ.to_config(AppConfig)

@pytest.fixture(name="app")
def _app(app_cfg):
    return make_app(app_cfg)

@pytest.fixture(name="client")
def _client(app):
    c = httpx.Client(app=app)

    yield c

    c.close()
```

At this point you can even parametrize your `app` fixture!

---

The last piece of the puzzle is how you access your config. Again, if you import it from a module that loads it on import time, there's nothing you can do except monkeypatching.

The solution lies in adding the config somehow to an application or request objects that you can access from your views. That's something you would do in the `make_app()` function.

**Comment by adrianovieira** [comment]
> The problem you're running into is exactly the reason why this kind of global configuration (that afaik has been popularized by Flask) is problematic.
> 
> Your config.py is the interface to the world and CONFIG is loaded on import time – there isn't much you can do here except monkeypatching, which would be my reluctant suggestion for a quick fix.
> 
> In a more general vein, what I do in my projects is having one application entry point that does the loading of environments (for wsgi apps, I call them `wsgi.py`): they import Config from `.config`, load it, configure logging, and then call an app factory that instantiates the application (in Flask's case using Blueprints – I presume FastAPI has an equivalent):
> 
> ```python
> import environ
> 
> from .app_maker import make_app
> from .config import AppConfig
> from .logging import setup_logging
> 
> app_cfg = environ.to_config(AppConfig)
> 
> setup_logging(app_cfg)
> application = make_app(app_cfg)
> ```
> 
> And now I run e.g. `gunicorn app.wsgi:application` (`:application` is default & optional)
> 
> That means I can configure my application like I want for every test, without patching around the environment:
> 
> ```python
> def pytest_configure():
>     for k, v in [
>         ("ENV", "test"),
>         ("SECRETS_INI", "test-secrets.ini"),
>     ]:
>         os.environ["APP_" + k] = v
> 
> @pytest.fixture(name="app_cfg", scope="session")
> def _app_cfg():
>     """
>     Loads the configuration delayed, i.e. after pytest_configure was able to
>     patch the environment.
>     """
>     return environ.to_config(AppConfig)
> 
> @pytest.fixture(name="app")
> def _app(app_cfg):
>     return make_app(app_cfg)
> 
> @pytest.fixture(name="client")
> def _client(app):
>     c = httpx.Client(app=app)
> 
>     yield c
> 
>     c.close()
> ```
> 
> At this point you can even parametrize your `app` fixture!
> 
> The last piece of the puzzle is how you access your config. Again, if you import it from a module that loads it on import time, there's nothing you can do except monkeypatching.
> 
> The solution lies in adding the config somehow to an application or request objects that you can access from your views. That's something you would do in the `make_app()` function.

Hi, hynek.
Thx for the quick answer.

I am not sure if your approach solves the issue here. It is for the same environment variable which can have different values depending on the context it is running on.
So we need to check in advance how the app behaves by setting those values on test time.

What if the app needs the environment variable, e.g: APP_ENV, and its values **staging**, **prod**, etc?

I don´t know how to config pytest to set those new values in order to environ-config get the new value for APP_ENV in each test case.

What I can do in this situation?

**Comment by hynek** [comment]
The point I was trying to make is to detach your application from the **loading** of your configuration.

IOW: you write a `make_app(cfg)` function that takes a (in your case) `_config.Config` and returns a configured web application, leaving out config-loading from your tests altogether. You can instantiate Config directly with whatever values you want.

Concretely with your fixtures you would replace the imports and do something like this:

```python
from fastapi.testclient import TestClient

from main import make_app

@pytest.fixture
def cfg():
    # you can either instantiate your `Config` directly, load it from environment,
    # or pass a fake environ to `to_config` here -- choice is yours.
    return environ.to_config()

@pytest.fixture
def client_env(cfg):
    cfg.place = "EU"
    
    yield TestClient(
        make_app(cfg)  # <--
    )
```

That's the clean / correct way.

---

If that refactoring that I've outlined is too much for you, you can always YOLO it with monkeypatching (e.g. pytest's `monkeypatch.setattr(_config, "Config", your_test_config)` if you only access it directly in your views. But then the web application itself can't depend on values from the config because you're instantiating the `app = FastAPI()` at import time too.

**Comment by hynek** [comment]
I have added a brief how-to guide to the documentation: https://environ-config.readthedocs.io/en/latest/testing.html
