### ISSUE TITLE
Type hints only support bare `@environ.config` without () or passing args

### ISSUE THREAD

**Issue by felixhuettner** [hynek/environ-config#53]
With (probably) https://github.com/hynek/environ-config/commit/683b1294af08bfce495f8bb7ca3723ea34c49894 typehints for the public apis where introduced (which i really like).

However it seems like that these typehints produce issues if you use `environ.config()`.

Using the following example (which works technically fine) we see issues when validating it with mypy.

```python
import environ

@environ.config()
class TestConfig:
    test_var = environ.var()

print(environ.to_config(TestConfig))
```

mypy outputs: 

```
$ mypy test.py 
test.py:4: error: <nothing> not callable  [misc]
Found 1 error in 1 file (checked 1 source file)
```

This can also be reproduced allthought with a slightly different error:

```python
import environ

class TestConfig:
    test_var = environ.var()

Test2 = environ.config(TestConfig, prefix="a")

print(environ.to_config(Test2))
```

```
$ mypy test.py
test.py:8: error: Argument 1 to "to_config" has incompatible type "TestConfig"; expected "Type[<nothing>]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by hynek** [comment]
Right, the problem is the calling version of environ.config that I never use myself and therefore forgot about it:

This works:

```python
@environ.config
class TestConfig:
    test_var = environ.var()

print(environ.to_config(TestConfig))
```

**Comment by ocardia** [comment]
We often don't want a prefix, so instead of [the default `APP` one](https://github.com/hynek/environ-config/blob/main/src/environ/_environ_config.py#L41-L49), we set it as an empty string.
This code below still fails with mypy in the same way as mentioned by @felixhuettner:
```py
import environ


@environ.config(prefix="")
class TestConfig:
    test_var = environ.var()


print(environ.to_config(TestConfig))
```

Is there an alternative way to specify an empty prefix in the code?

**Comment by hynek** [comment]
Does https://github.com/hynek/environ-config/pull/56 fix it for y'all?

**Comment by ocardia** [comment]
Yes, it does indeed! Thanks, and sorry for replying so late.

**Comment by hynek** [comment]
fix is on pypi
