### ISSUE TITLE
`AppConfig.generate_help`

### ISSUE THREAD

**Issue by vlcinsky** [hynek/environ-config#6]
Currently, one can print help calling `environ.generate_help(AppConfig).

Is it worth to extend PR #2 and beside `AppConfig.from_environ` provide also `AppConfig.generate_help`?

**Comment by vlcinsky** [comment]
PR #7 created.

To resolve (rare but possible) situation, that given class methods clashes with intended configuration class attributes, I added parameters allowing to rename the methods or prevent their creation completely (using "" or None).

``environ.config(from_environ="fr_env", generate_help="gen_hlp")``

**Comment by hynek** [comment]
This has been fixed by #7
