### ISSUE TITLE
`isort` pre-commit checks might fail due to local config

### ISSUE THREAD

**Issue by vlcinsky** [hynek/environ-config#8]
In PR #7 and one previous one I have run into an issue, that `isort` `pre-commit` check passed locally (using `tox -e ling`) and failed on Travis or vice versa.

As @hynek noted, the cause was local `isort` configuration. In my own case, there were `.editorconfig` and `.isort` files, which participated on the problem. After the files were renamed, the issue was gone.

It seems like `isort` (and possibly `black`?) could be affected by higher level configuration files.

One option to try is to specify **complete** `isort` configuration on project level. This way higher level configs would have no chance to influence the check.

**Comment by hynek** [comment]
Pretty sure black is safe.  If you think a complete isort configuration might solve this, I'd be super happy for PRs against any of my project. 😅

**Comment by vlcinsky** [comment]
@hynek I am also struggling with black versus isort issues. If I happen to meet reasonable solution, I will remember to share it with your projects.

**Comment by hynek** [comment]
I think isort changed behavior by now? In any case nothing _we_ can do about.
